#pragma config(UART_Usage, UART1, User_Control)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                   VEX Cortex UART Test
//
// Simple program to test user control over the VEX Cortex UART ports.
//
// 1. The two ports are looped back-to-back.
//
// 2. One port simply outputs characters with hex values 0, 1, 2, ... 255, 0, 1, 2, ...
//
// 3. The "UARTReceive" task grabs the characters from the receive UART and verifies that they are
//    in the above sequence.
//
// Various peg counts are used to accumulate total characters transmitted, received and "out of
// sequence" counts. These can be viewed in the ROBOTC debugger.
//
// NOTE: Internally the firmware uses interrupt handlers to buffer the characters transmitted and
//       received. The buffers are about 25 characters in length. If user program does not extract
//       the characters fast enough the older characters are simply discarded.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task UARTReceive();
int rcvChar;

task main()
{
  // Setup the two UART ports

  //configureSerialPort(uartOne, uartUserControl);
  //configureSerialPort(uartTwo, uartUserControl);
  setBaudRate(uartOne, baudRate115200);

  while (getChar(uartOne) != -1) // Purge existing chars from buffer
  {}

  StartTask(UARTReceive);
}

task UARTReceive()
{
  while (true)
  {
    // Loop forever getting characters from the "receive" UART. Validate that they arrive in the expected
    // sequence.

    rcvChar = getChar(uartOne);
    if (rcvChar == -1)
    {
      // No character available

      wait1Msec(2); // Don't want to consume too much CPU time. Waiting eliminates CPU consumption for this task.
      continue;
    }

    if (rcvChar == 'a')
    {
    	motor[rightMotor] = 127;		  // Motor on port2 is run at full (127) power forward
    }

    if (rcvChar == 'b')
    {
    	motor[rightMotor] = 0;		  // Motor on port2 is run at full (127) power forward
    }
  }
}
